[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solotto_rafle = "CVJwPBbBwcdmFJtHZQVzc9czXLyG5iHFshs5iZ1KBoQv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aaa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
